---
    environment: production
    chdir: /home/mat/www/best-asot/current
    address: 127.0.0.1
    port: 3720
    pid: /home/mat/www/best-asot/shared/pids/thin.pid
    rackup: /home/mat/www/best-asot/current/config.ru
    log: /home/mat/www/best-asot/shared/log/thin.log
    max_conns: 1024
    timeout: 30
    max_persistent_conns: 512
    daemonize: true

